### ISSUE TITLE
Fails when use systemjs.config.js

### ISSUE THREAD

**Issue by manish-panwar** [tomwanzek/d3-ng2-service#27]
My issue is similar to https://github.com/tomwanzek/d3-ng2-service/issues/11

Just so you know, I am using UMD packages, and still see the problem.

I am attaching package.json, app module and systemjs. I highly appreciate your help!

Given below is error I get :

> diagnostic:19 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/traceur
	Error: XHR error (404 Not Found) loading http://localhost:3000/traceur
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (https://unpkg.com/zone.js@0.6.25?main=browser:647:29)
	    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.6.25?main=browser:236:37)
	    at Zone.runTask (https://unpkg.com/zone.js@0.6.25?main=browser:136:47)
	    at XMLHttpRequest.ZoneTask.invoke (https://unpkg.com/zone.js@0.6.25?main=browser:304:33)
	Error loading http://localhost:3000/traceur
	Unable to load transpiler to transpile http://localhost:3000/node_modules/d3-ng2-service/index.js

[Archive.zip](https://github.com/tomwanzek/d3-ng2-service/files/674379/Archive.zip)

**Comment by manish-panwar** [comment]
Sorry, I didn't get 

> After further review, the issue should be addressed on the side of the module loader configuration (i.e. systemjs), so that the loader imports ES6 modules. This is required to obtain live-bindings necessary or d3.event to work.

I just started working on Angular.

**Comment by tomwanzek** [comment]
@manish-panwar My apologies for letting this issue slumber for longer than I should have. My initial response under #11 is still valid in principle. I.e. currently the published package support only imports based on ESM module format. When using a bundler, the bundler must be configured to support such imports. The `module` entry point is an ESM module compiled to ES5 target. The `es2015` entry point is a ESM module compiled to ES2015 target.

As a matter of managing scope here, I cannot provide comprehensive support on bundler configuration, with the information above, it is best to use the bundler/third party plug-in documentation in combination with StackOverflow.

Currently, I am not providing a `UMD` module entry point which might have made your life easier with `system.js`. As I mentioned before, I encountered some issues when using Rollup to create the bundle which seem related to the way D3 itself is published (i.e. its approach to using the `d3` global). I may re-consider this, as the guidelines for 3rd party Angular libraries and the related tooling are finally maturing. (I.e. see angular/angular#16486 and the starters in [angular-quickstart-lib](https://github.com/filipesilva/angular-quickstart-lib) and [generator-angular2-library](https://github.com/jvandemo/generator-angular2-library)).

I.e. conceivably, I may create a major release going forward which moves towards an Angular module rather than the bare bones service. I am closing this issue for now, however. Thanks for understanding.
