### ISSUE TITLE
Question: what does this service provide that you do not get by simply importing d3 directly?

### ISSUE THREAD

**Issue by billdwhite** [tomwanzek/d3-ng2-service#28]
I've been able to use d3 in my Angular 2 Typescript application created using angular-cli by adding  this to my package.json in the dependencies section:

`"d3": "^4.4.0"`

and this to my package.json in the devDependencies section:

`"@types/d3": "^4.4.0"`

and then using these imports in my TS files:
```

import * as d3 from 'd3';
import {
    Selection,
    Axis,
    ScaleLinear
} from 'd3'; // I am using these imports to get specific types 
```

So what does this d3-ng2-service give me that I am not already getting from just using d3 directly?

**Comment by tomwanzek** [comment]
A few considerations to explain:
* The intent was to access D3 idiomatically as a service which is instantiated as a singleton.
* A primary concern was, where D3's event handling is used, the live link to the `d3.event`, if used, should not accidentally broken.
* The service was written, before the bundle definitions for the standard D3 bundle could be published on DefinitelyTyped/@types.
* The service is not an exact replica of the D3 standard bundle, e.g. **d3-request** is omitted in favour of using Angular for http.
* The intent was to have something  for rapid prototyping, rather than a perfectly tailored minimal d3 feature set for a specific project.

All in all, if you are mindful of the event handling in D3 vs Angular and the cross-module prototype extensions used in D3, you are able to directly import the required functionality.

It kind of depends on exactly what D3 features you use.

That, in a nutshell, was the main background. 😄

**Comment by billdwhite** [comment]
Ok, thanks for the explanation

**Comment by impankratov** [comment]
@tomwanzek maybe this description could be added to the readme file? I think that could help people to quickly and easily understand the purpose of this project.

**Comment by tomwanzek** [comment]
@impankratov Thanks for the suggestion, I will consider an expanded "intended use" section.
