### ISSUE TITLE
Property 'json' doesn't exist on type 'd3'

### ISSUE THREAD

**Issue by AlexBokhankovich** [tomwanzek/d3-ng2-service#30]
I'm trying to implement d3 example [http://bl.ocks.org/mbostock/4062045](http://bl.ocks.org/mbostock/4062045) using d3-ng2-service. I got d3 instance by _this.d3 = d3Service.getD3();_ and then I try to call _d3.json()_ function 
`this.d3.json("miserables.json", function(error, graph){});`
In this case compiler throws error "Property 'json' doesn't exist on type 'd3'"
"d3-ng2-service": "1.5.3",

What is the proper way to resolve this?

**Comment by tomwanzek** [comment]
`json` is a method of the **d3-request** module. By design, I have chosen _not_ to include this module with **d3-ng2-service**.

The rationale is simply to use Angular methods for handling http, rather than using D3. So the recommended approach would be to use Angular's http service instead.

Hope this clarifies.

**Comment by AlexBokhankovich** [comment]
Yes, that makes sense. Thank you for clarification.
