### ISSUE TITLE
Dendrogram link/arc issue

### ISSUE THREAD

**Issue by kingo999** [tomwanzek/d3-ng2-service#31]
Hi Tim,
Great service ! you're examples worked out of the box :-)
I'm trying to implement the D4 version of a cluster dendrogram (http://bl.ocks.org/mbostock/4063570).
However, I'm running into a problem which most likely isn't related to the service but I'm hoping you can help.
In my implementation, the links between nodes are filled on.
I've attached the source and screen shot of the issue.
Hope you can shed some light on this.
Dave
![capture1](https://cloud.githubusercontent.com/assets/20421943/22175703/9b814ea4-dffa-11e6-918f-e909bac59d4e.PNG)
[d3Component.txt](https://github.com/tomwanzek/d3-ng2-service/files/721263/d3Component.txt)

**Comment by tomwanzek** [comment]
As you suggested, is not an issue with the service. So in principle, stackoverflow should be a better place for this kind of question.

However, in short, your implementation likely did not implement the styling applied to the links in the referenced bl.ock. I.p., the style rule for `fill: none` is missing, e.g.:
```css

.link {
  fill: none;
  stroke: #555;
  stroke-opacity: 0.4;
  stroke-width: 1.5px;
}
```

Hope this solves your problem, otherwise, please use SO for follow-up. Thanks for understanding 😄 . T
