### ISSUE TITLE
Property Links does not exists(is undefined) of type force()

### ISSUE THREAD

**Issue by mvala** [tomwanzek/d3-ng2-service#77]
I have similar problem as 
https://stackoverflow.com/questions/42194486/d3-ng2-service-error-property-links-does-not-exists-of-type-force
But after applyign fix it doensn't work for me. Here is may source code.

https://gitlab.openbrain.sk/mvala/bpt-webapp/blob/master/src/app/shared/d3/bpt/bpt.component.ts

Can you give me hint what to do?

**Comment by tomwanzek** [comment]
@mvala It seems you are referencing the SO post with the solution to your problem. However, the source code your referenced does not actually apply the key fixes I suggested in my SO post.

Specifically, if you re-read my SO solution, you will see that `d3.forceSimulation<YourNodeType, YourLinkType>()` and `simulation.force<ForceLink<YourNodeType, YourLinkType>>('link')` are invoked with generic parameters set to correspond to the node data type and link data type applicable to your data structure. I.e. the interfaces `YourNodeType` and `YourLinkType` have to be provided by you, as appropriate to your problem domain.

If you follow the instructions in the post, and possibly re-read the extensive JSDoc comments in the typescript definitions file for **d3-force** it should all fall into place.

I am closing the issue here, as it does not seem to reflect a problem with the service or the definitions. Should following the provided instructions not address your problem,  please feel free to post an issue on SO (or comment on the existing one). You can then simply ping me here under this issue here, and I will respond on SO.

Cheers. 😄

**Comment by mvala** [comment]
@tomwanzek , thanks for your help. I added type Node and Link
https://gitlab.openbrain.sk/mvala/bpt-webapp/tree/master/src/app/shared/d3/models
and after applying 

https://gitlab.openbrain.sk/mvala/bpt-webapp/blob/master/src/app/shared/d3/bpt/bpt.component.ts#L81
i get error
```
src/app/shared/d3/bpt/bpt.component.ts (81,19): Untyped function calls may not accept type arguments.
```

**Comment by tomwanzek** [comment]
@mvala A couple of things: Your local `simulation` variable is not properly defined/assigned. It should be defined as `let simulation: Simulation<YourNodeType, YourLinkType>;` and assigned as
```ts
      simulation = d3.forceSimulation<YourNodeType, YourLinkType>(this.nodes)
        .force("charge", d3.forceManyBody<YourNodeType>())
        .force("center", d3.forceCenter<YourNodeType>(this.width / 2, this.height / 2))
        .on("tick", ticked);
```

Note, that I avoided your usage of `Node` and `Link` simply because `Node` is a TypeScript "reserved" name, you are overloading.

With these changes, the error on line 81 will disappear. However, you are not defining and setting the Link force  before trying to retrieve it.

Should you experience any further issues building out your force simulation, please use StackOverflow for further clarifications. Unfortunately, I have to keep the scope of the issues in this repo managed to bugs and feature requests. Thanks for understanding.

**Comment by mvala** [comment]
Thanks for help. I will do my next interaction on StackOverflow
